apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  selector:
    app: chatapp
    tier: backend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: http

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: auth
spec:
  selector:
    matchLabels:
      app: chatapp
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: chatapp
        tier: backend
    spec:
      containers:
      - name: auth
        image: noelberistain/auth
        ports:
        - containerPort: 5000
          name: http